# Generated by Django 5.2.2 on 2025-06-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
# ссылка на предыдущую миграцию
    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
