# Generated by Django 5.2.2 on 2025-06-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_created_at_post_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='content',
        ),
    ]
